### PR TITLE
Lineoperations: version compare

### PR DESCRIPTION
**Pull request by smostertdev**
This PR is in response to #944.

Changes:
- Changed preferences to radio buttons to support multiple compare types.
lineops-version-compare-pref
- add "version compare" using filevercmp from coreutils

Notes:
- filevercmp is copied directly from coreutils's sort
https://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/filevercmp.c

I'm open to hear any suggestions/improvements.

### CODE REVIEW

**Comment by elextr** [comment]
Unfortunately filevercmp.c is GPL 3 and line operations is GPL 2 and those can't be combined, [see GNU](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)

**Comment by smostertdev** [comment]
Can I update the lineoperations license to GPLv3+ without issues? I guess I would have to get permission from anybody who made changes to lineoperations under the old license.
Would changing this license to GPLv3 cause problems in the future?

**Comment by elextr** [comment]
> I guess I would have to get permission from anybody who made changes to lineoperations under the old license.

That is what other projects that have changed licenses did yeah, my glance at git said not many people, and hopefully they will reply yes to a request for permission.

> Would changing this license to GPLv3 cause problems in the future?

Doubt it, there is at least one plugin with GPL3 license already (commander) and Geany itself is GPL2+ which is compatible.

**Comment by smostertdev** [comment]
I am closing this since I cannot merge it until I get this licensing resolved. I will open it if I figure things out.

**Comment by nomadbyte** [comment]
Could the version-sort be done with `strverscmp()` instead of `filevercmp()` from coreutils?

There're some differences, but for the general use like "file-1.9" vs. "file-1.10" the `strverscmp()` should do just fine. And it's part of `glibc` (well, `#define _GNU_SOURCE 1`), so no need to copy the original sources into the project and thus deal with this license harmonization issue.

**Pull request closed without merging**
