### PR TITLE
lineoperations: remove every n-th line

### PR DESCRIPTION
**Pull request by LarsGit223**
Imlements a new feature which allows to remove every n-th line. The user can enter the value of 'n' in a dialog. Implements #772.

### CODE REVIEW

**Comment by LarsGit223** [comment]
**Don't merge yet!** There is an error: need to add lineoperations to  POTFILES.in. Will do that tomorrow.

**Comment by LarsGit223** [comment]
Done. Updated POTFILES.in and also completed the README.

**Comment by frlan** [comment]
@smostertdev  should take over review maybe

**Comment by LarsGit223** [comment]
@frlan: we have nearly waited 2 month for a reply. I vote for merging this. It's quite a simple change and my tests looked good. Of course you can test it yourself if you like.

**Comment by elextr** [comment]
@smostertdev is the lineoperations maintainer I think.

**Comment by LarsGit223** [comment]
@elextr: yeah, but he didn't reply so I contacted frlan as he seems to be kind of the manager of geany-plugins.

**Comment by frlan** [comment]
I cannot do anything about how people responses. However, I did not found anything cruzial while reading over code. Let's test it in practice.

**Comment by LarsGit223** [comment]
@frlan: of course you can't. Please don't get me wrong: I did not mean to criticise you or smostertdev. It's just that it is a simple change and I think it's better to merge it at some point than to keep it open for several months. If it was a larger PR - yeah then we definitely would need to wait.

**Comment by elextr** [comment]
@LarsGit223 my comment was actually just meant to be a "subtle"??? re-ping :)

**Comment by smostertdev** [comment]
Glad to see that everyone is more on top of things than me. I just double checked it, compiled it and tested it and it looks great. Don't see any issues with to code, well written @LarsGit223

**Pull request merged**
