### PR TITLE
markdown: Remove an unused define

### PR DESCRIPTION
**Pull request by b4n**
Untested, but should be fine

### CODE REVIEW

**Comment by codebrainz** [comment]
Seems OK if it's not used and is causing grief.

**Comment by b4n** [comment]
> and is causing grief.

Probably not much, but that's one path less to worry about

**Comment by codebrainz** [comment]
OK by me then. I probably thought of a use for it at some point and just didn't need it or stopped needing it.

**Comment by geanyadmin** [comment]
> OK by me then. I probably thought of a use for it at some point and just
> didn't need it or stopped needing it.

If we merge #406 it'd become the same as PLUGINDATADIR, so you could use
that instead in the future.

**Comment by frlan** [comment]
@b4n Can you rebase it after the 1.27 as I woul direct merge it in

**Pull request merged**
