### PR TITLE
Cleanup: fixed usage of '#include "geanyplugin.h"'

### PR DESCRIPTION
**Pull request by LarsGit223**
Nothing more to say.

### CODE REVIEW

**Comment by elextr** [comment]
IIUC <> is for including system files, and despite its delusions of grandeur I don't think Geany is guaranteed to be in the list of system search directories.

**Comment by codebrainz** [comment]
https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html

> I don't think Geany is guaranteed to be in the list of system search directories.

It is, by the build system.

**Comment by elextr** [comment]
From the link:

```
"#include "file"    This variant is used for header files of your own program.
```

Sure GCC allows you to abuse the convention, but that doesn't mean you should.

**Comment by LarsGit223** [comment]
> #include \<file>
> 
>This variant is used for system header files. It searches for a file named file in a standard list of system directories. You can prepend directories to this list with the -I option (see Invocation).
> 

Isn't this the normal way to do it? The ```geanyplugin.h``` file is not part of geany-plugins but part of geany.

**Comment by codebrainz** [comment]
> Isn't this the normal way to do it?

It is. `geanyplugin.h` is a system include provided by `libgeany`, not local to plugins.

**Comment by kugel-** [comment]
Doesn't really matter if you use `""` or `<>`, the only difference is that `""` first looks in the location of the source file that is being compiled (I believe it's actually the working directory of the compiler), whereas `<>` looks only in paths provided on the command line and default include dirs (/usr/include) (`""` also looks in these paths).

So for geanyplugin.h you need the include path on the command line, so both `<>` and `""` are equally correct. But, by convention, you should prefer `<>` for headers that don't belong to your package, which is the case here.

**Pull request merged**
