### PR TITLE
projectorganizer : add shortcut to focus sidebar project tab

### PR DESCRIPTION
**Pull request by AlicVB**
So one can easily switch between tabs with keyboard.

This is my first contribution here, I hope I've done everything correctly...
Thanks

### CODE REVIEW

**Comment by techee** [comment]
@AlicVB Isn't Geany's "Focus->Switch to Sidebar" keybinding enough for this purpose?

**Comment by AlicVB** [comment]
well, not really as there's many tabs in sidebar.
I mainly use this new shortcut to switch between sidebar tabs with keyboard... (essentially between symbols and project tabs in my case)

**Comment by techee** [comment]
OK, should be addressed by #920

**Comment by techee** [comment]
Meh, just now I noticed this wasn't a bug report but actually a pull request - could have saved me some work. In my patch I just avoided assigning tab number which is probably better because the number can get wrong when some plugins add/remove new tabs to/from the sidebar.

**Pull request closed without merging**
