### PR TITLE
Geanypy proxy and keybindings

### PR DESCRIPTION
**Pull request by kugel-**
This is a mirror of https://github.com/codebrainz/geanypy/pull/37. @codebrainz said he's fine if this gets merged into G-P first.

Anyway, the commits tell the story. This PR converts geanypy to a proxy plugin (needs Geany git master/1.26), and then adds the long-awaited keybindings support.

With this, python plugins are just like other plugins w.r.t to the PM dialog, configuration and keybindings

### CODE REVIEW

**Comment by kugel-** [comment]
I do want this merged for 1.26, I hope we can manage it.

**Comment by codebrainz** [comment]
You should ping [the maintainer](https://github.com/geany/geany-plugins/blob/master/MAINTAINERS#L141) :)

I can't remember if I asked this yet, but does it break people's existing plugins?

**Comment by frlan** [comment]
Folks, we do have string freeze and release is next week. Unless there are real good reasons I think we shouldn't merge it for 1.26.

**Comment by kugel-** [comment]
@frlan this doesn't introducenew strings, and we're not formally feature frozen yet. On the other hand this are real improvements to geanypy, especially keybindings have been long asked for. It also fixed the other bug where geanypy would be disabled while python plugins are loaded.

@codebrainz all existing plugins continue to work. The only thing is that their configure implementation needs to be updated, and until then you cannot configure them. But they can read their existing configuration and still function as before

**Comment by frlan** [comment]
This merge will break current Python plugins in some way with a very low time in response. It changes basic things inside geanypy and is depending on a fresh introduced binding in Geany core. I know you might dislike this decision, but due to this I will add this PR to 1.27 and will not merge it for 1.26.

**Comment by codebrainz** [comment]
> @codebrainz all existing plugins continue to work. [...]

I just tested the PR against upstream and my simple plugin wasn't available after the PR. I'd say that doesn't qualify as "continue to work" :) I wonder if the GeanyPy loader could somehow locate and adapt old scripts to continue to work (even without `configure()`)?

**Comment by kugel-** [comment]
Am 8. November 2015 02:12:47 MEZ, schrieb Matthew Brush <notifications@github.com>:
>> @codebrainz all existing plugins continue to work. [...]
>
>I just tested the PR against upstream and my simple plugin wasn't
>available after the PR. I'd say that doesn't qualify as "continue to
>work" :) I wonder if the GeanyPy loader could somehow locate and adapt
>old scripts to continue to work (even without `configure()`)?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geany/geany-plugins/pull/295#issuecomment-154768791

That's unexpected. Can you paste the plug-in somewhere? 

I tested against the shipped ones and one of a irc user.

**Comment by codebrainz** [comment]
@kugel- http://pastebin.geany.org/vvr42/

I just took the Hello World one and renamed it a bit. It's file is at `$HOME/.config/geany/plugins/geanypy/plugins`.

**Comment by kugel-** [comment]
Am 8. November 2015 08:00:45 MEZ, schrieb Matthew Brush <notifications@github.com>:
>@kugel- http://pastebin.geany.org/vvr42/
>
>I just took the Hello World one and renamed it a bit. It's file is at
>`$HOME/.config/geany/plugins/geanypy/plugins`.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geany/geany-plugins/pull/295#issuecomment-154780187

Ah, I forgot thatched plugins have to be placed directly under $HOME/.config/geany/plugins/now, since they are loaded by geany now

**Comment by kugel-** [comment]
I agree that disqualifies "continue to work"

**Comment by codebrainz** [comment]
Though it's a better place for "thatched" plugins, in the long run :)

**Comment by frlan** [comment]
Should be closed with merging in of #384

**Pull request closed without merging**
