### PR TITLE
geanypy: Drop use of the most obvious deprecated Geany API

### PR DESCRIPTION
**Pull request by b4n**
Also introduce the Document.reload_force() alias to Document.reload_file(), as per non-deprecated Geany API.

@codebrainz @elextr

### CODE REVIEW

**Comment by techee** [comment]
LGBI.

@elextr I, too, don't know what I'm doing so if there's some other place where the depreciation should be mentioned, please fix it - it's your plugin after all :-P.

**Comment by elextr** [comment]
Better push it to upstream codebrainz/geanypy

**Comment by elextr** [comment]
@techee  its not my plugin, random people who commit stuff to it have just taken over its maintainership.

**Comment by elextr** [comment]
See #435 

This commit was not approved by the maintainer.

**Comment by techee** [comment]
> @techee its not my plugin, random people who commit stuff to it have just taken over its maintainership.

@elextr OK. 

>This commit was not approved by the maintainer.

I've previously asked Colomban and Frank if I can merge the Colomban's deprecation-removal patches since they have been lying here for months and the plugin maintainers haven't merged them yet (and most probably won't if they didn't until now), see

https://github.com/geany/geany-plugins/pull/369

**Comment by elextr** [comment]
On 9 June 2016 at 23:50, Jiří Techet <notifications@github.com> wrote:

> @techee <https://github.com/techee> its not my plugin, random people who
> commit stuff to it have just taken over its maintainership.
>
> @elextr <https://github.com/elextr> OK.
>
> This commit was not approved by the maintainer.
>
> I've previously asked Colomban and Frank if I can merge the Colomban's
> deprecation-removal patches since they have been lying here for months and
> the plugin maintainers haven't merged them yet (and most probably won't if
> they didn't until now), see
>
​You didn't even ping before doing it.
​
​I had asked that the deprecation message be put into the ​docstring, which
had not occurred.

As I said in my maintainer resignation, Geany-plugins has become untenable
for maintainers.

**Comment by b4n** [comment]
> ​I had asked that the deprecation message be put into the ​docstring, which had not occurred.

Okay, I didn't get it was a request for this to be acceptable.  I'd be happy to add it, I'd just need to know how it should be done.  Is there a way to do that further than writing some random sentence?

**Comment by elextr** [comment]
@b4n, AFAIK just use text, probably adding something like "[Deprecated, use ...]" would do.

**Comment by techee** [comment]
> You didn't even ping before doing it.

Sorry. My impression was the maintainers have been pinged enough when the pull request was made and didn't respond for 3 months which I interpreted as either "looks OK" or "don't care about Geany any more".
​
> ​I had asked that the deprecation message be put into the ​docstring, which
had not occurred.

Sorry, I didn't interpret your message as not approving the patch.

Since I know nothing about the plugin I didn't explore where such a docstring belongs. And adding it is quite trivial for someone who does - which I assumed was you. Also my impression was that merging this doesn't break anything and that the docstring patch could be added later quite independently.

> As I said in my maintainer resignation, Geany-plugins has become untenable
for maintainers.

Again sorry if merging this and other similar patches looked unfriendly - I definitely didn't want to do something against plugin maintainer's will and didn't expect this reaction. Since many plugins are unmaintained and even when they are officially maintained the maintainers don't respond, I think it's necessary to do some minor cleanups from time to time without having to wait (possibly infinitely) for the maintainer's approval.

**Pull request merged**
