### PR TITLE
autotools: Add a flag to enable or disable all plugins

### PR DESCRIPTION
**Pull request by b4n**
This allows to change the default for whether every plugins are enabled or disabled, effectively allowing to easily select either all, or only a specific set of plugins.

To force enable all plugins:
	`configure --enable-all-plugins`

To force enable all plugins, but disable Addons:
	`configure --enable-all-plugins --disable-addons`

To force enable all plugins, but Addons which is checked automatically:
	`configure --enable-all-plugins --enable-addons=auto`

To disable all plugins, but force enable Addons:
	`configure --disable-all-plugins --enable-addons`

### CODE REVIEW

**Comment by codebrainz** [comment]
It's not clear (to me) from the M4 whether `--enable-all-plugins=auto` is accepted or the default (you mention "force" so it sounds like not). It might be useful and seems to be supported in the `_GP_ARG_DISABLE_ALL` part.

Other than that, I think this is a really good idea.

**Comment by codebrainz** [comment]
I think someone said this is already supported by Waf build system, but it might be useful to add `all` as a plugin name that can be used with `--list-plugins`, `--enable-plugins`, and `--skip-plugins` to make it explicit?

**Comment by b4n** [comment]
> It's not clear (to me) from the M4 whether `--enable-all-plugins=auto` is accepted or the default (you mention "force" so it sounds like not). It might be useful and seems to be supported in the `_GP_ARG_DISABLE_ALL` part.

You can pass `auto` and it's the default, which doesn't change the current behavior.  Passing auto however is pretty much useless as it has virtually no effect.

**Comment by frlan** [comment]
Shall we put this into 1.25?

**Comment by b4n** [comment]
@frlan I think we should, but I wished for some comments here from the people complaining about the missing feature.  Without them, I can't really know if they appreciate this solution, or if they would rather have some other interface.

@zhekov do you have an opinion on this?

**Comment by b4n** [comment]
Added some docs

**Pull request merged**
