### PR TITLE
Add missing sign for cppcheck --template argument

### LINKED ISSUE #1304: 2.0.0: test suite fails with cppcheck 2.13.1 (unrecognized command line option: "--template")
```console
+ cd geany-plugins-2.0.0
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in po
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/po'
INTLTOOL_EXTRACT="/usr/bin/intltool-extract" XGETTEXT="/usr/bin/xgettext" srcdir=. /usr/bin/intltool-update --gettext-package geany-plugins --pot
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/po'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/po'
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
if [ -r missing -o -r notexist ]; then \
  exit 1; \
fi
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/po'
Making check in utils
Making check in src
/usr/bin/make  check-local
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/utils/src'
/usr/bin/cppcheck \
        -q --template gcc --error-exitcode=2 \
        --library=../../build/cppcheck-geany-plugins.cfg \
        -I/usr/include/geany \
          \
        .
cppcheck: error: unrecognized command line option: "--template".
make[3]: *** [Makefile:882: check-cppcheck] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/geany-plugins-2.0.0/utils/src'
make[2]: *** [Makefile:751: check-am] Error 2
make[1]: *** [Makefile:568: check-recursive] Error 1
make: *** [Makefile:613: check-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by eht16**
Closes #1304.

### CODE REVIEW

**Comment by eht16** [comment]
@elextr I couldn't resist to credit this great and very sophisticated change to you as you already solved the mystery in https://github.com/geany/geany-plugins/issues/1304#issuecomment-1912600670!

**Comment by elextr** [comment]
I just RTFineM for cppcheck, but I don't use it, so thats why I referred it to @b4n who wrote it originally or anybody else who has a new enough version that `--template` is an official option, not UU (undocumented unofficial).

**Comment by eht16** [comment]
I tested the `--template=gcc` format locally with the latest cppcheck version and it works.

The idea by using the specific "gcc" template was probably that the output can be parsed by Geany out of the box using the default error message regex for C/C++ files. But this is just a guess.

I noticed new "undefined macro" errors while testing and added those as well (same story as in #1196).

With these changes, "make check" ran fine on my system.

**Comment by eht16** [comment]
See also #1310 for an improved CI build with using the current "cppcheck" version instead of the dated version from the CI runner image.

**Pull request merged**
