### PR TITLE
[Debugger] Windows port for geany's "debugger" plugin.

### PR DESCRIPTION
**Pull request by vkochan**
Hi, 
This is my 1'st little testable version

### CODE REVIEW

**Comment by frlan** [comment]
@vkochan  Can you please review Enrico's suggestions and maybe update your PR?

**Comment by vkochan** [comment]
Meanwhile I don't have a setup with windows machine, I dropped using windows by default, so I am not
sure if I can help with supporting of this patch.

**Comment by frlan** [comment]
Am 11.03.2015 um 08:37 schrieb Vadim Kochan:
> Meanwhile I don't have a setup with windows machine, I dropped using
> windows by default, so I am not
> sure if I can help with supporting of this patch.

OK. I keep it open and maybe somebody is able to adopt it.

**Comment by frlan** [comment]
I will close the MR yet as it's quiet ancient already and nobody seemed to take over.

**Pull request closed without merging**
