### PR TITLE
Update pt_BR.po

### PR DESCRIPTION
**Pull request by liomarhora**

### CODE REVIEW

**Comment by eht16** [comment]
Are these changes intended?

**Comment by liomarhora** [comment]
> Are these changes intended?
 
Yes, I'm removed the old library devhelp2.

**Comment by eht16** [comment]
I don't get it.
Currently, there is no Devhelp in GIT master. So, strictly the *.po files should be updated to remove the previous translations.

But since you are already about to re-add the plugin, updating the translation files would be done best after your changes from #1242 have been merged.

So, why do you want to comment one (to me random) translation string in GIT master from the not yet available Devhelp plugin?

**Comment by elextr** [comment]
Won't it be commented automatically anyway if devhelp is still missing when the message files are re-merged before next release?

IMO leave it to the tools.

**Comment by liomarhora** [comment]
I must have duplicated it due to using two computers
I use 2 PCs to update the plugin.
It seems to me that I created 2 forks for the same plugin.
should I keep both or migrate to the one with the highest number of commits?

**Comment by eht16** [comment]
I suggest to simply close this PR and focus on #1242 which has the same changes.

**Comment by liomarhora** [comment]
> Sugiro simplesmente fechar este PR e focar no [nº 1242](https://github.com/geany/geany-plugins/pull/1242) , que tem as mesmas alterações.
Ok.

**Comment by liomarhora** [comment]
have you tested the plugin in your Geany IDE

**Pull request closed without merging**
