### PR TITLE
Update da.po (making it completly untranslated)

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by frlan** [comment]
Why this step?

**Comment by scootergrisen** [comment]
Because completely untranslated is better then having 3 translated strings and some incorrect fuzzy strings.

**Comment by frlan** [comment]
Are you planning to restart a new translation?

**Comment by scootergrisen** [comment]
> 
> 
> Are you planning to restart a new translation?

no

**Comment by frlan** [comment]
I had some discussion with ppl I know about this. Even though I'm not a fan of this I'm going to merge this.

**Pull request merged**
