### PR TITLE
FIX: GeanyLua: 'Choose' dialog size/appearance (b4n's patch)

### PR DESCRIPTION
**Pull request by Skif-off**
See issues [690](https://github.com/geany/geany-plugins/issues/690), [1374](https://github.com/geany/geany-plugins/issues/1374).

### CODE REVIEW

**Review by b4n — APPROVED** [review]
LGTM.  Only thing is that it's probably not necessary to keep GTK2 support given it has been dropped from Geany since 1.38; but it's fine to keep the check and do this later on.

**Comment by xiota** [comment]
I've updated the lua plugin and updated status to "odd fixes".  I've confirmed issue #1374 and that this PR fixes it.

@Skif-off Up to you whether you want to remove the gtk version check before merge.  There are others, so they can be sweeped up together in a future PR.  If you intend to leave the check, please comment, so your intention is clear.

**Comment by Skif-off** [comment]
Removed.

**Review by xiota — APPROVED** [review]

**Comment by xiota** [comment]
@b4n I think this is ready to merge.

**Pull request merged**
