### PR TITLE
Add note to plugins which are currently not actively maintained

### PR DESCRIPTION
**Pull request by frlan**
This is based on MAINTAINERS file. 

Idea is, to show enduser that the plugin might need its help.

### CODE REVIEW

**Comment by codebrainz** [comment]
I don't like the wording "no active development" since that doesn't really mean anything but it might turn users to a different plugin. For example the Scope plugin is probably the best debugging plugin, but this marks it with a big warning (which doesn't mean anything).

IMO it would be better to put a note at the end of the description like "This plugin currently has no maintainer. Would you like to help by contributing to this plugin?" or something like that.

If not that, then it should at least just say "No active maintainer" at the end of the description, not in stars at the very front.

**Comment by frlan** [comment]
I did not at it at the end of description as I wanted to make it prominent to the user.

**Comment by frlan** [comment]
@codebrainz Do you have a suggestion for a better wording? We got a bunch of orphaned and odd-fixes  plugins which might not work as long as nobody is willing to adopt them.

**Comment by codebrainz** [comment]
I gave two in my previous message:

> This plugin currently has no maintainer. Would you like to help by contributing to this plugin?

And

> No active maintainer

**Comment by frlan** [comment]
Ahdammid. Thanks for rereading your post to me. Good ideas. I will change my PR

**Comment by frlan** [comment]
@codebrainz  I did rewording. I hope I improved it a little ;)

**Pull request merged**
