### PR TITLE
scope: prevent usage of invalid iters (GtkTreeeIter)

### PR DESCRIPTION
**Pull request by LarsGit223**
This fixes the crash described in #824 (and two more potential crashes).

### CODE REVIEW

**Comment by b4n** [comment]
This is not really the right fix, `g_return_*if_fail()` is supposed to catch programming error, to check the contract between the caller and the callee.  Admittedly here the values are accessed before the contract is checked, which is probably worth fixing, but the bug itself is that these functions get called with values they are not supposed to.

**Comment by LarsGit223** [comment]
I will try to find the trouble source. Anyway I would like to keep the existing changes for better stability in case of an error.

**Comment by LarsGit223** [comment]
Done. The wrong call came from ```stack_entry()``` because of not checking the result of ```gtk_tree_selection_get_selected()```.

**Comment by LarsGit223** [comment]
@b4n: do you request more changes? I would like to merge this soon.

**Pull request merged**
