### PR TITLE
geanypg: Update to Scintilla 5.1.5 SCI_GETSELTEXT change

### PR DESCRIPTION
**Pull request by techee**
See Scintilla release notes here

https://www.scintilla.org/ScintillaHistory.html

and https://github.com/geany/geany/issues/3095

### CODE REVIEW

**Comment by elextr** [comment]
Should not use send message directly, should use `sci_get_selection_contents()`

**Comment by techee** [comment]
> Should not use send message directly, should use sci_get_selection_contents()

Good point, then it doesn't need the API bump change.

But I think we should actually do ABI bump because the previous version won't work correctly, what do you think?

**Comment by elextr** [comment]
> But I think we should actually do ABI bump because the previous version won't work correctly, what do you think?

Well thats part of Geany, and discussions elsewhere, not this PR, and as @kugel- pointed out elsewhere that won't help if the plugin gets re-compiled, but its better than nothing.

**Comment by kugel-** [comment]
LGTM

**Review by kugel- — APPROVED** [review]

**Comment by techee** [comment]
I'm merging this as I think the patch is OK - it should be the last piece of the Scintilla 5.1.5 aftermath.

**Pull request merged**
