### PR TITLE
Update travis to system with c++11 compiler

### PR DESCRIPTION
**Pull request by elextr**
Test to fix Travis, do not merge unless Travis passes

### CODE REVIEW

**Comment by elextr** [comment]
Ok, the Travis failure is nothing to do with this change, should be ok to merge.

@eht16  add-ons seems to fail cppcheck?

**Comment by eht16** [comment]
Probably fixed in https://github.com/geany/geany-plugins/commit/544e9f6b57927eb98bd8daadb1b7bd2b9a3b2c89.
Seems it is the old cppcheck version on that old Ubuntu 14.04 build box at Travis.
cppcheck 1.80 on my system doesn't complain. Anyway, the initialization won't hurt.

Maybe you could merge master into this branch and try again?

**Comment by codebrainz** [comment]
This closes #596 (adding link to keep myself from getting confused).

**Comment by elextr** [comment]
Ok, looks good to merge.

**Comment by codebrainz** [comment]
Looks OK by inspection, after rebasing this branch on master to get 544e9f6, I would squash 82727a9 into 69a271d since the former just fixes the latter.

Seems not risky since it just messes with the CI, not any code.

**Pull request merged**
