### PR TITLE
xmlsnippets: Drop use of the most obvious deprecated Geany API

### PR DESCRIPTION
**Pull request by b4n**
Not tested.

@earshinov

### CODE REVIEW

**Comment by techee** [comment]
@frlan @b4n Is it OK if I go through all the patches of @b4n related to the deprecation warnings in plugins and if I find them OK, to merge them? The plugin authors haven't responded so far and they probably won't until the release and it would be nice to have a less noisy build for the next release.

**Comment by b4n** [comment]
@techee would be nice by me, yeah

**Comment by frlan** [comment]
@techee Yepp.

**Comment by techee** [comment]
LGBI.

**Pull request merged**
