### PR TITLE
Waf: Allow to explicitly set plugin name

### PR DESCRIPTION
**Pull request by b4n**
Also use the new feature to fix *git-changebar* plugin name and installation directory for common files.

### CODE REVIEW

**Comment by eht16** [comment]
I'm ok with this change.
Just being curious, why do you want to change the internal name from "gitchangebar" to "git-changebar"?

**Comment by b4n** [comment]
> Just being curious, why do you want to change the internal name from "gitchangebar" to "git-changebar"?

Just because it's the name used with Autotools and wanted the build systems to agree, and also to some extent to match the directory name in the tree.

However, another solution to keep consistency without this would be just stripping the dash from everywhere, I don't mind either way.

**Comment by eht16** [comment]
Me neither :).
Having this change might help in the future for other plugins, so why not.

**Comment by b4n** [comment]
Alternatively I could also simply set the `name` to "Git-ChangeBar" and not mind the combination of CamelCase and dashes (which I actually don't) -- or event not use camel-case in the log domain.

**Pull request merged**
