### PR TITLE
scope: port to GTK3.

### PR DESCRIPTION
**Pull request by LarsGit223**
I ported the scope plugin to GTK3 and VTE 2.91.

### CODE REVIEW

**Comment by Skif-off** [comment]
@LarsGit223 
Why ```GP_CHECK_PLUGIN_GTK3_ONLY```? Is plugin don't support build with GTK2 now?

**Comment by LarsGit223** [comment]
@Skif-off: no. As the PR is right now, it would only support GTK3.

**Comment by Skif-off** [comment]
@LarsGit223 
Sorry, I didn't understand :) Is Geany drop to support GTK2?

**Comment by LarsGit223** [comment]
@Skif-off:
No. By default geany compiles/is built for GTK2. If you specify the option ```--enable-gtk3``` on build then it will be build for GTK3. Then only plugins would work with that version of geany which support GTK3.

Which OS/distro do you use? Many linux distros support both GTK versions.

**Comment by LarsGit223** [comment]
To be explicit: Geany will still support GTK2. It will not be dropped.

**Comment by Skif-off** [comment]
@LarsGit223 
Thanks, I was confused by the [GP_CHECK_PLUGIN_GTK**3_ONLY**](https://github.com/geany/geany-plugins/pull/697/files#diff-c6ec9ad09f6351d19420270032720e7eR4).

P.S. I use Xubuntu 17.10, but I compile on my own (I use [PR 1752](https://github.com/geany/geany/pull/1752)) and [I don't like GTK3](https://github.com/geany/geany/issues/1746).

**Comment by elextr** [comment]
@Skif-off To be even more explicit, geany will still support gtk2, its just the changes in this PR make this plugin gtk3 only.  Which is why I keep repeating myself that it should be a separate plugin so it leaves the GTK2 version available for those lucky people where it does not hang Geany.

@LarsGit223 I don't suppose by any chance that you have removed the recursion that I understand is the trigger for the Glib bug?

**Comment by LarsGit223** [comment]
@elextr: no, the changes are only regarding GTK3 and VTE compatibility.

**Comment by LarsGit223** [comment]
@frlan: please don't merge this yet as there is still an open discussion how to proceed regarding GTK2 and GTK3 support.

**Comment by frlan** [comment]
I will not merge it when disabling Gtk2 without suitable replacement for Gtk2 users

**Comment by LarsGit223** [comment]
I am closing this ion favour of PR #750.

**Pull request closed without merging**
