### PR TITLE
 Geanypy proxy and keybindings

### PR DESCRIPTION
**Pull request by kugel-**
This is reworked version if #295 

I opened a new PR because I don't have incremental commits available (I cherry picked from the upstream PR https://github.com/codebrainz/geanypy/pull/37) and didn't want to destroy the comments there.

Anyway, the commits tell the story. This PR converts geanypy to a proxy plugin (needs Geany git master/1.26), and then adds the long-awaited keybindings support.

With this, python plugins are just like other plugins w.r.t to the PM dialog, configuration and keybindings

According to #295 @codebrainz is fine if G-P merges it first (@codebrainz please speak up if you changed your mind).

### CODE REVIEW

**Comment by kugel-** [comment]
@frlan @elextr ping :)

**Comment by elextr** [comment]
Well, I can't test it and its too big for more than a scan inspection, but it has been beaten up on upstream a bit so I'm ok with it.

BTW has it ever been tested on windows?

**Comment by elextr** [comment]
@frlan can't see the official label to add so just saying ok here :)

**Comment by sagarchalise** [comment]
@kugel- I have been testing this enhancement in geanypy. It doesnot load plugins in `~/.config/geany/plugins` directory. I get `ImportError`. I have been testing these plugins 

https://github.com/sagarchalise/geanypy-emmet
https://github.com/sagarchalise/geanypy-reStructured-preview

**Comment by kugel-** [comment]
@sagarchalise it never did that. It thinkpad you have to Do it manually (for extra modules). Or are you saying your main plugins file can't be loaded?

**Comment by kugel-** [comment]
@frlan ping

**Comment by codebrainz** [comment]
You guys are crazy merging such a big change so close to release :)

**Comment by sagarchalise** [comment]
@kugel- My main plugin file is loaded only from `/usr/local/lib/geany` path but not from config directory.

**Comment by kugel-** [comment]
Try latest master, I made a bug fix regarding that.

**Comment by elextr** [comment]
> You guys are crazy merging such a big change so close to release :)

But upstream so totally tested it :)

**Pull request merged**
