### PR TITLE
GeanyLua: Update for Scintilla 5.1.4

### LINKED ISSUE #1118: Update GeanyLua for Scintilla 5
After https://github.com/geany/geany/pull/2867 has been merged, the GeanyLua plugin needs to be updated to work with the new Scintilla version.

Currently, compilation fails as follow:
```
make: Entering directory '/home/enrico/projects/geany-plugins/geanylua'
Making all in docs
make[1]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/docs'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/docs'
Making all in examples
make[1]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples'
Making all in dialogs
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples/dialogs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples/dialogs'
Making all in edit
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples/edit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples/edit'
Making all in info
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples/info'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples/info'
Making all in scripting
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples/scripting'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples/scripting'
Making all in work
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples/work'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples/work'
make[2]: Entering directory '/home/enrico/projects/geany-plugins/geanylua/examples'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples'
make[1]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua/examples'
make[1]: Entering directory '/home/enrico/projects/geany-plugins/geanylua'
  CC       libgeanylua_la-glspi_sci.lo
  CC       geanylua_la-geanylua.lo
In file included from glspi_sci.c:11:
glspi_sci.h:369:39: error: ‘SCI_GETTWOPHASEDRAW’ undeclared here (not in a function); did you mean ‘SCI_GETPHASESDRAW’?
  369 |         {"GETTWOPHASEDRAW", SLT_BOOL, SCI_GETTWOPHASEDRAW, SLT_VOID, SLT_VOID},
      |                                       ^~~~~~~~~~~~~~~~~~~
      |                                       SCI_GETPHASESDRAW
  CCLD     geanylua.la
glspi_sci.h:370:39: error: ‘SCI_SETTWOPHASEDRAW’ undeclared here (not in a function); did you mean ‘SCI_SETPHASESDRAW’?
  370 |         {"SETTWOPHASEDRAW", SLT_VOID, SCI_SETTWOPHASEDRAW, SLT_BOOL, SLT_VOID},
      |                                       ^~~~~~~~~~~~~~~~~~~
      |                                       SCI_SETPHASESDRAW
glspi_sci.h:711:32: error: ‘SCI_SETLEXER’ undeclared here (not in a function); did you mean ‘SCI_SETILEXER’?
  711 |         {"SETLEXER", SLT_VOID, SCI_SETLEXER, SLT_INT, SLT_VOID},
      |                                ^~~~~~~~~~~~
      |                                SCI_SETILEXER
glspi_sci.h:716:40: error: ‘SCI_SETLEXERLANGUAGE’ undeclared here (not in a function); did you mean ‘SCI_GETLEXERLANGUAGE’?
  716 |         {"SETLEXERLANGUAGE", SLT_VOID, SCI_SETLEXERLANGUAGE, SLT_VOID, SLT_STRING},
      |                                        ^~~~~~~~~~~~~~~~~~~~
      |                                        SCI_GETLEXERLANGUAGE
glspi_sci.h:717:40: error: ‘SCI_LOADLEXERLIBRARY’ undeclared here (not in a function)
  717 |         {"LOADLEXERLIBRARY", SLT_VOID, SCI_LOADLEXERLIBRARY, SLT_VOID, SLT_STRING},
      |                                        ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:862: libgeanylua_la-glspi_sci.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/enrico/projects/geany-plugins/geanylua'
make: *** [Makefile:916: all-recursive] Error 1
make: Leaving directory '/home/enrico/projects/geany-plugins/geanylua'
``

### PR DESCRIPTION
**Pull request by xiota**
Using `geanylua/util/mkiface.lua` to generate new `glspi_sci.h`.  At least, it compiles and appears to run.

Resolves #1118.

### CODE REVIEW

**Comment by xiota** [comment]
Force push to include "GeanyLua" in the commit log.

**Comment by elextr** [comment]
@xiota @Skif-off Scintilla 5 has split the lexers from the widget, you need to map Lexilla as well as Scintilla.

**Comment by elextr** [comment]
@Skif-off then you don't need `SETILEXER` since the pointer that you pass to it can only be obtained from the lexilla interface.

**Comment by elextr** [comment]
Even if it could be added, `setilexer` probably shouldn't, if a plugin sets a lexer directly it is likely to break lots of filetype things that depend on the known lexer, set the filetype via Geany which will set the appropriate lexer, not the lexer directly.

**Comment by Skif-off** [comment]
Any news? New Scintilla/Lexilla in upstream now.

**Comment by xiota** [comment]
@Skif-off Thanks for the reminder.  I've been feeling like I've been forgetting something.

The only change is to regenerate `glspi_sci.h`.  The only script I have that sends scintilla messages still works:
```Lua
geany.scintilla ("SCI_SETEDGEMODE", 3, 3)
geany.scintilla ("SCI_MULTIEDGECLEARALL", 0, 0)

-- Colors are in BGR order
geany.scintilla ("SCI_MULTIEDGEADDLINE", 60, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 72, 0xffd0b0) -- blue
geany.scintilla ("SCI_MULTIEDGEADDLINE", 80, 0xffc0ff) -- purple
geany.scintilla ("SCI_MULTIEDGEADDLINE", 88, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 96, 0xa0b0ff) -- red
geany.scintilla ("SCI_MULTIEDGEADDLINE", 104, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 112, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 120, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 128, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 136, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 144, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 152, 0xe5e5e5)
geany.scintilla ("SCI_MULTIEDGEADDLINE", 160, 0xe5e5e5)
```

**Comment by elextr** [comment]
Sorry but I have neither time nor inclination to review this.

**Comment by xiota** [comment]
@Skif-off Can you let me know whether you'll be able to do a code review on this?  Thanks.

**Comment by Skif-off** [comment]
@xiota
I am not a programmer, but I'm not very stupid and I have some experience - AutoIt (GUI and CLI), JScript (in the first, plugins for AkelPad), VBScript (various automation), Lua, Python (a little). Also I added AutoIt support to Geany and use it. So, I am not an expert :)
As I see this commit looks good and works. (And we can't build plugins without this PR.)

**Comment by xiota** [comment]
@Skif-off...  Thanks for looking and testing.

 @eht16 and @elextr had requested that we review each other's PRs, and it doesn't hurt to have extra eyes.

I just saw geany/geany#3046... So it may be yet longer before this can be merged ☹️

**Comment by eht16** [comment]
I cannot properly review this either.

My vote goes for updating this PR shortly (if possible) after https://github.com/geany/geany/pull/3046 is merged and then merge this one to get G-P building again at all. In the worst case, GeanyLua might remain a little broken but the rest of G-P will compile again.

**Comment by elextr** [comment]
> GeanyLua might remain a little broken but the rest of G-P will compile again.

We could always switch the default for Geany lua to disable until its fixed so everything else works in the meantime.

**Comment by eht16** [comment]
And keep this PR unmerged until a Lua developer find this PR and reviews it, just by luck?
After it is updated for Scintilla 5.1.5, I would do a basic code review so that it doesn't the much wanted* spyware or any obvious and then finally merge it.

* negate this as desired :D

**Comment by Skif-off** [comment]
@eht16 
>  updating this PR shortly (if possible) after [geany/geany#3046](https://github.com/geany/geany/pull/3046) is merged

As I see, [geany/geany#3046](https://github.com/geany/geany/pull/3046) does not contain changes that matter for this plugin (in this case GeanyLua uses only ```Scintilla.h``` and ```Scintilla.iface```).

**Comment by eht16** [comment]
@Skif-off true, the #3046 does not change the generated `gsdlg.h` and also don't contain any other obvious changes which are related. So this PR is independent of the pending Scintilla update.

It doesn't look bad, I just did not yet understand why the many parameter handling changes are necessary.
The commit message of b0b1b2acc226938dc37723cd1d2366fc2785b611 is not very verbose. I see there are new parameter types added but also some existing code moved and so potential logic changed. This is probably ok, I just cannot see why.
@xiota can you shed some light on this?

**Comment by xiota** [comment]
Original code for `glspi_scintilla()` has:
* some check for when missing arguments are allowed
* switch for wparam
* near-identical switch for lparam
* switch for result

Changes:
* Removed extraneous nested parentheses from the parameter check for missing arguments.
* Added switch to ignore some lexer messages because lexilla is now separate from scintilla.  It was [pointed out](https://github.com/geany/geany-plugins/pull/1123#issuecomment-947310520) that messing with the lexer could cause problems elsewhere in Geany.
* Combined the near identical argument-handling switch statements into a static function.  The number of scintilla types went from ~10 to ~70.  Keeping the switches separate could lead to potentially difficult to track problems if they go out of sync.
* Added new types to the result switch.  Basically treating most types as int.  This can be shuffled around later, as needed.

**Comment by eht16** [comment]
Thanks, that helped reading the diff.

For me the code looks ok and I would like to merge this in a few days if nobody stops me.

**Pull request merged**
