### PR TITLE
GeanyLua: Add function geany.reloadconf() 

### PR DESCRIPTION
**Pull request by Skif-off**
Reload most of Geany's configuration files without restarting, as menu item "Tools"->"Reload Configuration" or ```geany.reload_configuration()``` [from GeanyPy](https://geanypy.readthedocs.io/en/latest/api.html#geany.reload_configuration).

### CODE REVIEW

**Comment by Skif-off** [comment]
Sorry, I used the wrong branch for cloning, I will fix it.

**Comment by frlan** [comment]
@Skif-off  would you mind to rebase and stash your branch based on recent git master?

**Comment by Skif-off** [comment]
@frlan done.

**Comment by Skif-off** [comment]
I wanted to correct something in the documentation (formatting only, more convenient to read + links for navigation): how much time do I have before the release 1.33?

**Comment by frlan** [comment]
No,. Please run git rebase master on your branch and make a force push to the branch.

**Comment by Skif-off** [comment]
@frlan 
Sorry, I'm a little confused :( Is now it happened? Otherwise it's easier for me to re-add PR.

**Comment by codebrainz** [comment]
Please don't abuse the bug tracker to avoid learning Git :)

I think what @frlan is asking is to squash the commits together into one, and to rebase it on master so it merges cleanly (@frlan correct me if I'm wrong).

**Comment by Skif-off** [comment]
Sorry, maybe I am stupid, but I am doing my best :)

I don't know how to remove "Merge pull request #1 from geany/master" (synchronization with master). Is it possible?

**Comment by elextr** [comment]
@Skif-off yeah for git the console is better.

What I understand @frlan' is asking is for you to do a [git rebase](https://git-scm.com/docs/git-rebase) against the master branch to combine the two commits together and hopefully make the merge you did in your branch disappear (lesson: only ever pull Geany master into your master, not your branch).

`git rebase --interactive` makes it easier.

**Comment by Skif-off** [comment]
Big thanks to all of you, it seems, it's done.

But I have one problems: I did bad understand how I did it...

**Comment by frlan** [comment]
Much better ;) Thanks.

**Pull request merged**
