### PR TITLE
Windows installer: Migrate to NSIS 3.x

### PR DESCRIPTION
**Pull request by eht16**

### CODE REVIEW

**Comment by frlan** [comment]
@eht16  Any tests needed or just merging?

**Comment by eht16** [comment]
I tested the changes last week when creating the PR and I think the changes are simple enough. Most of the work has been done already when doing the same changes on the Geany installer a few months ago.

**Comment by elextr** [comment]
Ahh, the obligatory last minute windows change, the release can go ahead as soon as this is merged :grin:

**Comment by eht16** [comment]
@elextr did you expect anything else? :D

**Pull request merged**
