### PR TITLE
Utilities for Pair Tag Highlighter

### PR DESCRIPTION
**Pull request by sagarchalise**
I think these are useful to working with xml pair tags.

- Editor Menu option for jumping to matching tag
- Selecting to matching tag

### CODE REVIEW

**Comment by frlan** [comment]
@sagarchalise  Would you mind to rebase it on current HEAD

**Comment by sagarchalise** [comment]
@frlan Not sure this is what you wanted, but I have based the changes according to latest master.

**Comment by sagarchalise** [comment]
Had to create another PR as this got closed during my rebasing...

**Comment by codebrainz** [comment]
You could have just reopened it.

**Pull request closed without merging**
